name: Setup

description: Sets up PHP and Composer

inputs:
  php-version:
    description: The PHP version(s) you wish to use.
    required: true
  php-extensions:
    description: The PHP extensions you want to install.
    required: false
    default: dom, curl, libxml, mbstring, zip, pcntl, pdo, gd, redis, igbinary, msgpack, lzf, zstd, lz4, memcached, gm
  coverage:
    description: The coverage driver to use.
    required: false
    default: none

runs:
  using: composite
  steps:
    - name: Get PHP extensions cache hash
      id: php-extensions-cache-hash
      run: echo PHP_HASH=$(echo $PHP_EXTENSIONS | md5sum | awk '{print $1}' ) >> $GITHUB_ENV
      shell: bash

    - name: Setup cache environment
      id: extcache
      uses: shivammathur/cache-extensions@v1
      with:
        php-version: ${{ inputs.php-version }}
        extensions: ${{ inputs.php-extensions }}
        key: php-extensions-${{ env.PHP_HASH }}

    - name: Cache extensions
      uses: actions/cache@v4
      with:
        path: ${{ steps.extcache.outputs.dir }}
        key: ${{ steps.extcache.outputs.key }}
        restore-keys: ${{ steps.extcache.outputs.key }}

    - name: Setup PHP and composer
      id: setup-php
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ inputs.php_version }}
        extensions: ${{ inputs.php_extensions }}
        tools: composer:v2
        coverage: ${{ inputs.coverage }}

    - name: Get composer cache dir
      id: composer-cache-dir
      run: echo COMPOSER_CACHE_DIR=$(composer config cache-files-dir) >> $GITHUB_ENV
      shell: bash

    - name: Cache Dependencies
      uses: actions/cache@v4.1.1
      with:
        key: composer-cache-${{ hashFiles('**/composer.lock') }}
        path: ${{ env.COMPOSER_CACHE_DIR }}
        restore-keys: composer-cache-
