name: Laravel Pint

on:
  push:
    branches:
      - main

jobs:
  laravel-pint:
    runs-on: ubuntu-latest

    env:
      PHP_VERSION: '8.3'
      PHP_EXTENSIONS: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, gd, redis, igbinary, msgpack, lzf, zstd, lz4, memcached, gmp
      PHP_CACHE_KEY: extension-cache-v1

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Setup
        uses: ./.github/actions/setup
        with:
          php-version: '8.3'

      - name: Install Laravel pint
        run: composer global require laravel/pint

      - name: Run pint
        run: pint

      - name: Push Changes
        run: |
          git config user.name "gh-actions"
          git config user.email "gh@example.com"
          git add .
          git commit -m 'Laravel pint' || exit 0
          git push
